(() => {
  'use strict';

  // Lot verificat direct din PDF-ul oficial SNPAP 2011: enunt, variante si cheia
  // marcata in grila de raspuns. Au fost excluse itemii pentru care raspunsul depinde
  // mai mult de formularea unei bibliografii sau de o interpretare istorica decat de
  // un fapt singular neechivoc.
  const source = number => `SNPAP Târgu Ocna – Concurs de admitere, sesiunea septembrie 2011, Istoria românilor, Varianta I, întrebarea ${number}; grila oficială de răspuns publicată de SNPAP.`;

  window.registerQuestionBatch([
    ['2011-ist-001','istorie','autonomii-institutii','Țara Cărvunei era situată între:',['Carpați și Dunăre','Mangalia și Varna','Prut și Nistru','spațiul intracarpatic'],1,source(1),'Țara Cărvunei, formațiune politică dobrogeană medievală, era localizată în sudul Dobrogei, în zona dintre Mangalia și Varna.'],
    ['2011-ist-002','istorie','constitutii','Constituția din 1866 a inaugurat un regim politic de:',['monarhie constituțională','republică democratică','monarhie parlamentară','republică democratică'],0,source(2),'Constituția din 1866 a instituit monarhia constituțională în România.'],
    ['2011-ist-003','istorie','autonomii-institutii','Cronica lui Anonymus menționează voievodatele conduse de:',['Gyla și Menumorut','Gyla și Ahtum','Gelu, Glad și Menumorut','Litovoi și Seneslau'],2,source(3),'Gesta Hungarorum a lui Anonymus îi menționează pe Gelu, Glad și Menumorut.'],
    ['2011-ist-004','istorie','constitutii','Prin lovitura de stat din 1864, Cuza a impus un nou act constituțional numit:',['Statutul Dezvoltător al Convenției de la Paris','Convenția de la Paris','Regulamentele Organice','Constituția Cărvunarilor'],0,source(4),'În 1864 Alexandru Ioan Cuza a impus Statutul Dezvoltător al Convenției de la Paris.'],
    ['2011-ist-005','istorie','autonomii-institutii','Formațiunile politice locale conduse de Tatos, Seslav și Satza sunt menționate în lucrarea:',['Diploma cavalerilor ioaniți','Legenda Sfântului Gerald','Gesta Hungarorum','Alexiada'],3,source(5),'Tatos, Seslav și Satza sunt menționați de Ana Comnena în Alexiada.'],
    ['2011-ist-006','istorie','constitutii','Un prim proiect de constituție, elaborat la Iași în 1822, se numea:',['Constituția Cărvunarilor','Regulamentul Organic','Convenția de la Iași','Convenția de la Paris'],0,source(6),'Constituția Cărvunarilor a fost redactată în Moldova în 1822.'],
    ['2011-ist-007','istorie','autonomii-institutii','Diploma Cavalerilor Ioaniți a fost emisă în anul:',['1211','943','1247','1277'],2,source(7),'Diploma Cavalerilor Ioaniți a fost emisă de regele Béla al IV-lea în 1247.'],
    ['2011-ist-008','istorie','constitutii','Unificarea organizării de stat și a legislației menite să favorizeze progresul întregii națiuni, precum și înfăptuirea statului național unitar în 1918, a determinat:',['adoptarea unei noi Constituții','impunerea Constituției din 1866','modificarea unor articole din Constituția din 1866','adoptarea Constituției belgiene din 1831'],0,source(8),'Noua realitate politică și teritorială de după 1918 a determinat adoptarea Constituției din 1923.'],
    ['2011-ist-009','istorie','autonomii-institutii','Voievodul Litovoi și fratele său Bărbat s-au ridicat în anii 1277-1279 împotriva:',['suzeranității otomane','suzeranității maghiare','dominației tătare','dominației polone'],1,source(9),'Litovoi a intrat în conflict cu coroana maghiară, refuzând obligațiile de suzeranitate.'],
    ['2011-ist-010','istorie','constitutii','Prăbușirea regimului comunist din România și revenirea la un regim democratic după 1989 a impus:',['elaborarea unei noi Constituții','punerea în practică a articolelor Constituției din 1918','adoptarea Constituției franceze','adoptarea Convenției de la Paris'],0,source(10),'Schimbarea de regim după 1989 a fost urmată de elaborarea și adoptarea Constituției din 1991.'],
    ['2011-ist-011','istorie','autonomii-institutii','Prima etapă a întemeierii Moldovei a fost legată de:',['descălecatul lui Dragoș','descălecatul lui Negru Vodă','descălecatul lui Bogdan','descălecatul lui Ștefan'],0,source(11),'Prima etapă a formării statului medieval Moldova este asociată descălecatului lui Dragoș.'],
    ['2011-ist-012','istorie','constitutii','Prin Constituția de la 1923:',['Regatul României este un stat național unitar și indivizibil','se legifera regimul comunist','România se transforma în Republica Populară Română','România se transforma în Republica Socialistă România'],0,source(12),'Constituția din 1923 consacra România drept stat național, unitar și indivizibil.'],
    ['2011-ist-014','istorie','autonomii-institutii','Cronica domniei lui Ludovic, scrisă de Ioan de Târnave, semnalează transformarea într-un stat independent a:',['Țării Românești','Moldovei','Transilvaniei','Dobrogei'],0,source(14),'Cronica lui Ioan de Târnave consemnează afirmarea independenței Țării Românești față de coroana maghiară.'],
    ['2011-ist-015','istorie','romania-postbelica','Primul președinte al Prezidiului Marii Adunări Naționale a fost:',['Gheorghe Gheorghiu-Dej','Nicolae Ceaușescu','Petru Groza','Constantin I. Parhon'],3,source(15),'Constantin I. Parhon a fost primul președinte al Prezidiului Marii Adunări Naționale.'],
    ['2011-ist-016','istorie','romania-postbelica','Funcția de președinte al Republicii Socialiste România a fost înființată în:',['1974','1975','1976','1977'],0,source(16),'Funcția de președinte al RSR a fost creată în 1974.'],
    ['2011-ist-018','istorie','autonomii-institutii','Într-un document din 1324, Basarab era numit de către regalitatea maghiară:',['voievodul nostru transalpin','principe credincios','rege al vlahilor','rege credincios'],0,source(18),'Documentul regal din 1324 îl numește pe Basarab „voievodul nostru transalpin”.'],
    ['2011-ist-019','istorie','stat-modern','Conducătorul mișcării din 1821 din Țara Românească s-a numit:',['Alexandru Ioan Cuza','Tudor Vladimirescu','Nicolae Bălcescu','Mihail Kogălniceanu'],1,source(19),'Mișcarea din 1821 din Țara Românească a fost condusă de Tudor Vladimirescu.'],
    ['2011-ist-020','istorie','autonomii-institutii','Basarab I l-a asociat la tron pe fiul său:',['Vladislav Vlaicu','Mircea','Vlad','Nicolae Alexandru'],3,source(20),'Basarab I l-a asociat la domnie pe fiul său Nicolae Alexandru.'],
    ['2011-ist-021','istorie','stat-modern','În 1822, în Moldova este numit domn:',['Grigorie Dimitrie Ghica','Alexandru Ioan Cuza','Ioniță Sandu Sturdza','Nicolae Bălcescu'],2,source(21),'În 1822, odată cu revenirea la domniile pământene, în Moldova a fost numit Ioniță Sandu Sturdza.'],
    ['2011-ist-023','istorie','stat-modern','Convenția de la Balta-Liman a fost semnată între Rusia și Turcia în:',['1848','1849','1859','1866'],1,source(23),'Convenția de la Balta-Liman a fost încheiată în 1849.'],
    ['2011-ist-024','istorie','stat-modern','Documentul care a reafirmat autonomia Principatelor și le-a trecut sub garanția colectivă a celor șapte mari puteri s-a numit:',['Tratatul de la Paris','Convenția de la Paris','Statutul Dezvoltător al Convenției de la Paris','Constituția belgiană'],0,source(24),'Tratatul de pace de la Paris din 1856 a pus Principatele sub garanția colectivă a marilor puteri.'],
    ['2011-ist-025','istorie','autonomii-institutii','Mitropolia Moldovei, creată de Petru I, își avea sediul la:',['Suceava','Iași','Baia','Siret'],0,source(25),'Mitropolia Moldovei și-a avut sediul la Suceava.'],
    ['2011-ist-026','istorie','stat-modern','Actul prin care Principatele Unite, Moldova și Valahia, urmau să aibă fiecare câte un domnitor ales pe viață de Adunarea electivă din fiecare principat a fost:',['Convenția de la Paris','Tratatul de la Paris','Statutul Dezvoltător al Convenției de la Paris','Regulamentele Organice'],0,source(26),'Convenția de la Paris din 1858 stabilea alegerea câte unui domn în fiecare principat.'],
    ['2011-ist-028','istorie','stat-modern','Marile puteri întrunite la Paris la 26 martie/7 aprilie 1859 au recunoscut actul de la 24 ianuarie, cu excepția:',['Austriei și Imperiului Otoman','Rusiei, Austriei și Imperiului Otoman','Angliei, Rusiei, Austriei și Turciei','Prusiei, Rusiei și Turciei'],0,source(28),'Austria și Imperiul Otoman au refuzat inițial să recunoască dubla alegere a lui Alexandru Ioan Cuza.'],
    ['2011-ist-029','istorie','romania-postbelica','Regele Mihai I a fost obligat să abdice la:',['23 august 1944','6 martie 1945','19 noiembrie 1946','30 decembrie 1947'],3,source(29),'Regele Mihai I a fost constrâns să abdice la 30 decembrie 1947.'],
    ['2011-ist-030','istorie','constitutii','Conform prevederilor Statutului Dezvoltător al Convenției de la Paris, prin înființarea Senatului (Corpul Ponderator) se trecea de la:',['sistemul unicameral la cel bicameral','sistemul democratic la cel totalitar','monarhie constituțională la monarhie parlamentară','vot cenzitar la vot universal'],0,source(30),'Crearea Corpului Ponderator a transformat legislativul dintr-un sistem unicameral într-unul bicameral.'],
    ['2011-ist-031','istorie','autonomii-institutii','Ordonați cronologic: A. emiterea Diplomei cavalerilor ioaniți; B. începutul domniei lui Ștefan cel Mare; C. Transilvania devine provincie a Imperiului Habsburgic; D. întemeierea Mitropoliei Moldovei.',['CBDA','BACD','ADBC','DCBA'],2,source(31),'Ordinea este A-D-B-C: 1247, întemeierea Mitropoliei Moldovei, 1457 și instaurarea dominației habsburgice asupra Transilvaniei.'],
    ['2011-ist-032','istorie','stat-modern','Ordonați cronologic: A. izbucnirea revoluției din Moldova; B. Convenția de la Balta-Liman; C. alegerea ca domn a lui Alexandru Ioan Cuza în Țara Românească; D. emiterea Rezoluțiilor de către Adunările ad-hoc.',['ABDC','BDCA','DABC','CBAD'],0,source(32),'Ordinea este A-B-D-C: revoluția din 1848, Balta-Liman 1849, rezoluțiile din 1857 și alegerea din 24 ianuarie 1859.'],
    ['2011-ist-033','istorie','concert-european','Ordonați cronologic: A. adoptarea Constituției care consfințea Marea Unire; B. semnarea păcii dintre noul guvern bolșevic al Rusiei cu Puterile Centrale de la Brest-Litovsk; C. Adunarea Națională de la Alba Iulia hotărăște unirea Transilvaniei cu România; D. instaurarea pe tronul României a lui Ferdinand I.',['DBCA','ABCD','CBDA','BACD'],0,source(33),'Ordinea este D-B-C-A: 1914, martie 1918, 1 decembrie 1918, 1923.'],
    ['2011-ist-034','istorie','autonomii-institutii','Ordonați cronologic: A. prăbușirea regatului ungar; B. începutul domniei lui Roman I; C. descălecatul lui Bogdan; D. instalarea ungurilor în Panonia.',['BCDA','ABCD','DCBA','BDCA'],2,source(34),'Ordinea este D-C-B-A: stabilirea ungurilor în Panonia, descălecatul lui Bogdan, domnia lui Roman I și Mohács 1526.'],
    ['2011-ist-035','istorie','autonomii-institutii','Ordonați cronologic: A. începutul regimului fanariot în Țara Românească; B. întemeierea Mitropoliei Moldovei; C. sfârșitul domniei lui Mircea cel Bătrân; D. începutul domniei lui Petru I Mușat.',['DBCA','ACDB','BDCA','ABCD'],0,source(35),'Ordinea este D-B-C-A: Petru I Mușat, întemeierea Mitropoliei Moldovei, 1418, 1716.'],
    ['2011-ist-036','istorie','romania-postbelica','Ordonați cronologic: A. condamnarea intervenției statelor din Tratatul de la Varșovia în Cehoslovacia de către Nicolae Ceaușescu; B. sfârșitul colectivizării; C. greva minerilor din Valea Jiului; D. abdicarea regelui Mihai I.',['ABCD','DBAC','ACBD','DACB'],1,source(36),'Ordinea este D-B-A-C: 1947, 1962, 1968, 1977.'],
    ['2011-ist-037','istorie','stat-modern','Ordonați cronologic: A. constituirea Sfatului Țării; B. constituirea în Transilvania a Consiliului Național Român Central; C. proclamarea unirii necondiționate a Bucovinei cu Regatul României; D. votarea de către Sfatul Țării a unirii Basarabiei cu România.',['ADBC','BCDA','DCAB','DCAB'],0,source(37),'Ordinea este A-D-B-C: Sfatul Țării în 1917, unirea Basarabiei în martie 1918, CNRC în toamna lui 1918 și unirea Bucovinei în noiembrie 1918.'],
    ['2011-ist-038','istorie','concert-european','Ordonați cronologic: A. constituirea Înțelegerii Balcanice; B. Nicolae Ceaușescu este ales președinte al Republicii Socialiste România; C. intrarea României în Primul Război Mondial; D. aderarea României la Tripla Alianță.',['ACBD','DCAB','ABDC','CABD'],1,source(38),'Ordinea este D-C-A-B: 1883, 1916, 1934, 1974.'],
    ['2011-ist-039','istorie','constitutii','Ordonați cronologic: A. începe domnia lui Carol I; B. proclamarea Regatului; C. Parlamentul României votează legile de ratificare a unirii Basarabiei, Bucovinei și Transilvaniei cu România; D. este adoptată Constituția care consfințea înfăptuirea statului național unitar român.',['CADB','DBCA','BCDA','ABCD'],3,source(39),'Ordinea este A-B-C-D: 1866, 1881, ratificările unirii, apoi Constituția din 1923.'],
    ['2011-ist-040','istorie','autonomii-institutii','Ordonați cronologic: A. sfârșitul domniei lui Ștefan cel Mare; B. recunoașterea Mitropoliei Moldovei de către Bizanț; C. așezarea cavalerilor teutoni în Țara Bârsei; D. menționarea în documente a lui Leustachius voievod.',['DCBA','ACBD','ABCD','BCDA'],0,source(40),'Ordinea este D-C-B-A: Leustachius, 1211, recunoașterea Mitropoliei Moldovei și 1504.'],
    ['2011-ist-041','istorie','concert-european','Ordonați cronologic: A. atentatul de la Sarajevo; B. ocuparea regiunii sudete din Cehoslovacia de către Germania; C. adoptarea Rezoluției Adunării ad-hoc a Moldovei; D. izbucnirea Primului Război Balcanic.',['CDAB','ACDB','BACD','ABCD'],0,source(41),'Ordinea este C-D-A-B: 1857, 1912, 1914, 1938.'],
    ['2011-ist-042','istorie','constitutii','Ordonați cronologic: A. aprobarea Constituției Republicii Socialiste România; B. adoptarea unei Constituții alcătuite după modelul Constituției sovietice în vigoare și care consfințea impunerea regimului comunist în România; C. adoptarea unei Constituții promulgate de Carol al II-lea prin decret regal; D. adoptarea Constituției care se referea la Principatele Unite Române ca un singur stat indivizibil sub denumirea de România.',['DCBA','ABCD','BACD','CDAB'],0,source(42),'Ordinea este D-C-B-A: Constituțiile din 1866, 1938, 1948 și 1965.'],
    ['2011-ist-043','istorie','diplomatie-conflict','Ordonați cronologic: A. încheierea tratatului dintre Mircea cel Bătrân și regele Ungariei, Sigismund de Luxemburg; B. prima ciocnire armată între români și otomani în vremea lui Vladislav Vlaicu; C. lupta de la Călugăreni; D. cruciada de la Nicopole.',['BADC','ABCD','CABD','DABC'],0,source(43),'Ordinea este B-A-D-C: confruntarea din vremea lui Vladislav Vlaicu, tratatul lui Mircea cu Sigismund, Nicopole și Călugăreni.'],
    ['2011-ist-044','istorie','autonomii-institutii','Ordonați cronologic: A. aderarea României la Tripla Alianță; B. crearea comitatului Bihor; C. excluderea românilor din Transilvania din sistemul națiunilor privilegiate; D. începutul domniei lui Nicolae Alexandru.',['BDCA','ACBD','DABC','ABCD'],0,source(44),'Ordinea este B-D-C-A: comitatul Bihor, Nicolae Alexandru, excluderea politică a românilor și aderarea la Tripla Alianță.' ]
  ]);
})();