(() => {
  'use strict';

  const S = {
    p1: "SNPAP Târgu Ocna – Admitere 2013, Istoria românilor, Varianta III, barem oficial, p. 1.",
    p2: "SNPAP Târgu Ocna – Admitere 2013, Istoria românilor, Varianta III, barem oficial, p. 2.",
    p3: "SNPAP Târgu Ocna – Admitere 2013, Istoria românilor, Varianta III, barem oficial, p. 3.",
    p4: "SNPAP Târgu Ocna – Admitere 2013, Istoria românilor, Varianta III, barem oficial, p. 4.",
    p5: "SNPAP Târgu Ocna – Admitere 2013, Istoria românilor, Varianta III, barem oficial, p. 5.",
    key: "SNPAP Târgu Ocna – Admitere 2013, Istoria românilor, grila oficială de răspuns."
  };

  const E = "Răspuns verificat în documentul oficial și în grila centralizată de răspuns.";

  window.registerQuestionBatch([
    ["2013-ist-001", "istorie", "autonomii-institutii", "Voievodatul lui Menumorut era situat în:", ["Crișana", "Banat", "Țara Făgărașului", "Dobrogea"], 0, S.p1, E],
    ["2013-ist-002", "istorie", "stat-modern", "Domnii pământeni numiți de Poartă în septembrie 1822 au fost:", ["Grigore al IV-lea Dimitrie Ghica și Gheorghe Bibescu", "Grigore Alexandru Ghica și Barbu Știrbei", "Grigore al IV-lea Dimitrie Ghica și Mihail Sturdza", "Grigore al IV-lea Dimitrie Ghica și Ioniță Sandu Sturdza"], 3, S.p1, E],
    ["2013-ist-003", "istorie", "constitutii", "Definirea statutului extern al țării, prin Constituția din 1866, a dat dovadă de:", ["precauție", "îndrăzneală", "independență", "perspicacitate"], 1, S.p1, E],
    ["2013-ist-004", "istorie", "autonomii-institutii", "Voievodatul lui Seneslau era situat în:", ["dreapta Oltului", "stânga Oltului", "dreapta Jiului", "Maramureș"], 1, S.p1, E],
    ["2013-ist-005", "istorie", "autonomii-institutii", "Inscripția de la Mircea Vodă a fost datată în anul:", ["943", "1111", "1176", "1230"], 0, S.p1, E],
    ["2013-ist-006", "istorie", "constitutii", "Conform Titlului III, articolul 93 din Constituția din 1866:", ["domnul numește și revocă pe miniștrii săi; sancționează și promulgă legile; are drept de amnistie în materie politică", "ocupă funcția de președinte al Consiliului de Miniștri; sancționează și promulgă legile; are drept de amnistie în materie politică", "ocupă funcția de Președinte al Înaltei Curți de Justiție și Casație; Domnul numește și revocă pe miniștrii săi; sancționează și promulgă legile", "are drept exclusiv de inițiativă legislativă; sancționează și promulgă legile; domnul numește și revocă pe miniștrii săi"], 0, S.p1, E],
    ["2013-ist-007", "istorie", "stat-modern", "Regulamentele Organice pot fi considerate:", ["„actul de naștere al constituționalismului în România”", "„actul de naștere al parlamentarismului în România”", "„actul de naștere al naționalismului în România”", "„actul de naștere al conservatorismului în România”"], 1, S.p1, E],
    ["2013-ist-008", "istorie", "autonomii-institutii", "Potrivit informațiilor transmise de Gesta Hungarorum, maghiarii au început cucerirea spațiului cuprins între Tisa, Crișuri și Someș la începutul secolului:", ["al X-lea", "al XI-lea", "al XIII-lea", "al IX-lea"], 0, S.p1, E],
    ["2013-ist-009", "istorie", "autonomii-institutii", "Ordinul Cavalerilor Teutoni a fost instalat în Țara Bârsei de către regele:", ["Andrei al II-lea", "Ludovic I de Anjou", "Carol Robert de Anjou", "Sigismund de Luxemburg"], 0, S.p1, E],
    ["2013-ist-010", "istorie", "stat-modern", "Conform Convenției de la Paris din 1858, cele două instituții comune ale Principatelor erau:", ["Comisia Centrală de la Focșani și Sfatul Domnesc", "Comisia Centrală de la Focșani și Înalta Curte de Justiție și Casație", "Înalta Curte de Justiție și Casație și Adunarea Legislativă", "Adunarea Legislativă și Comisia Centrală de la Focșani"], 1, S.p1, E],
    ["2013-ist-011", "istorie", "concert-european", "Armata română a pierdut în 3 ani de lupte în timpul celui de-Al Doilea Război Mondial:", ["625.000 militari", "815.000 militari", "218.000 militari", "925.000 militari"], 0, S.p1, E],
    ["2013-ist-012", "istorie", "diplomatie-conflict", "Mihai Viteazul încheia la Alba Iulia, la 20 mai 1595, un tratat cu:", ["Andrei Bathory", "Sigismund de Luxemburg", "Matei Corvin", "Sigismund Bathory"], 3, S.p1, E],

    ["2013-ist-013", "istorie", "diplomatie-conflict", "În 1600, Mihai Viteazul se intitula:", ["domn al Țării Românești", "domn al Țării Românești și Ardealului și Moldovei", "domn al Țării Românești și Ardealului", "domn al Moldovei și Ardealului"], 1, S.p2, E],
    ["2013-ist-014", "istorie", "concert-european", "Cedarea Basarabiei, a nordului Bucovinei și ținutului Herța s-a realizat în urma:", ["atacului URSS asupra României în 14 iunie 1940", "notelor ultimative din 26-27 iunie 1940", "capitulării Franței în fața Germaniei din 20 iunie 1939", "atacului Germaniei asupra URSS din 23 august 1939"], 1, S.p2, E],
    ["2013-ist-015", "istorie", "diplomatie-conflict", "După victoria împotriva otomanilor, Mihai Viteazul a încheiat cu habsburgii, în 1598, un tratat orientat împotriva:", ["habsburgilor", "otomanilor", "polonezilor", "papalității"], 1, S.p2, E],
    ["2013-ist-016", "istorie", "concert-european", "Cel De-al Doilea Război Mondial a izbucnit la:", ["1 septembrie 1939", "14 iulie 1939", "23 noiembrie 1939", "20 iunie 1940"], 0, S.p2, E],
    ["2013-ist-017", "istorie", "concert-european", "În 1934, convorbirile sovieto-române au fost conduse de miniștrii de externe:", ["Nicolae Titulescu și Maksim Litvinov", "Nicolae Titulescu și Viaceslav Molotov", "Nicolae Titulescu și Joachim von Ribbentrop", "Take Ionescu și Maksim Litvinov"], 0, S.p2, E],
    ["2013-ist-018", "istorie", "stat-modern", "Contestarea domniilor fanariote s-a făcut pe calea:", ["satirelor și scrisorilor politice", "memoriilor și scrisorilor politice", "pamfletelor și memoriilor politice", "satirelor și pamfletelor politice"], 2, S.p2, E],
    ["2013-ist-019", "istorie", "romania-postbelica", "Guvernul condus de Petru Groza a fost instaurat la:", ["23 august 1944", "28 februarie 1945", "6 martie 1945", "25 octombrie 1944"], 2, S.p2, E],
    ["2013-ist-020", "istorie", "stat-modern", "Domnia lui Ferdinand I este marcată și de:", ["adoptarea reformei agrare și votului universal", "instaurarea unui regim autoritar și votului universal", "adoptarea reformei teritorial-administrative și votului cenzitar", "adoptarea Convenției externe și înființarea ambasadelor"], 0, S.p2, E],
    ["2013-ist-021", "istorie", "stat-modern", "Conform Regulamentului Organic, Sfatul Domnesc era înlocuit cu:", ["Adunarea Obștească", "Consiliul Princiar", "Sfatul Administrativ", "Sfatul Popular"], 2, S.p2, E],
    ["2013-ist-022", "istorie", "stat-modern", "Guvernul revoluționar instaurat în iunie 1848 în Țara Românească era denumit:", ["căimăcămie", "locotenență Domnească", "guvern Central", "adunare Constituantă"], 1, S.p2, E],
    ["2013-ist-023", "istorie", "stat-modern", "În 1858 alegătorii se împărțeau în funcție de venit în:", ["alegători direcți și alegători indirecți", "alegători de peste 18 ani", "alegători de peste 21 ani", "alegători delegați"], 0, S.p2, E],
    ["2013-ist-024", "istorie", "autonomii-institutii", "Banatul a fost transformat în pașalâc în anul:", ["1522", "1541", "1456", "1683"], 0, S.p2, "Răspunsul reproduce baremul oficial. Itemul este carantinat deoarece anul corect al transformării Banatului în pașalâc este 1552, variantă absentă din subiect."],
    ["2013-ist-025", "istorie", "stat-modern", "Statutul Dezvoltător al Convenției de la Paris limita drepturile:", ["puterii executive", "puterii judecătorești", "puterii legislative", "puterii ecleziastice"], 2, S.p2, E],
    ["2013-ist-026", "istorie", "autonomii-institutii", "Gestiunea centrală a veniturilor domniei se afla sub autoritatea:", ["stolnicului", "marelui logofăt", "marelui vistier", "postelnicului"], 2, S.p2, E],
    ["2013-ist-027", "istorie", "stat-modern", "Monstruoasa coaliție s-a coagulat în jurul ideii înlocuirii lui Al. I. Cuza cu:", ["un principe austriac", "un reprezentant al dinastiei franceze", "un Hohenzollern acceptat de Marile Puteri", "un prinț străin"], 3, S.p2, E],
    ["2013-ist-028", "istorie", "concert-european", "În 1853, Principatele Române sunt ocupate militar de Rusia, care dorea să le folosească drept:", ["zonă de aprovizionare pentru armata sa", "cap de pod spre inima Imperiului Otoman", "zonă tampon între Marile Puteri", "zonă de protecție pentru creștinismul ortodox"], 1, S.p2, E],
    ["2013-ist-029", "istorie", "concert-european", "În 1856, sudul Basarabiei era retrocedat:", ["Moldovei", "Țării Românești", "Principatelor Unite", "Imperiului Otoman"], 0, S.p2, E],
    ["2013-ist-030", "istorie", "romania-postbelica", "Funcția de președinte al Republicii Socialiste România a fost instituită la:", ["10 mai 1974", "23 august 1973", "28 martie 1974", "10 februarie 1974"], 2, S.p2, E],

    ["2013-ist-031", "istorie", "autonomii-institutii", "Ordonați cronologic evenimentele: A. Constituirea de către regalitatea maghiară a primului comitat în Transilvania; B. Recunoașterea Mitropoliei de la Suceava de către Bizanț; C. Întemeierea primei Mitropolii a Țării Românești de la Curtea de Argeș; D. Bătălia de la Mohacs.", ["ADCB", "BADC", "ACBD", "BCAD"], 2, S.p3, E],
    ["2013-ist-032", "istorie", "constitutii", "Ordonați cronologic: A. Revizuirea Constituției din 1991; B. Elaborarea Constituției care consacra principiul supremației regelui și suprima separarea puterilor în stat; C. Elaborarea unei Constituții în societatea alcătuită după modelul Constituției sovietice în vigoare; D. Aprobarea Constituției Republicii Socialiste România.", ["BCDA", "CDAB", "ADBC", "DCAB"], 0, S.p3, E],
    ["2013-ist-033", "istorie", "stat-modern", "Ordonați cronologic evenimentele: A. Intervenția militară otomană care a pus capăt evenimentelor revoluționare în Țara Românească; B. Începe guvernarea Principatelor Române prin căimăcămie; C. Declanșarea Războiului Crimeii; D. Încheierea Convenției de la Balta-Liman.", ["DCAB", "CABD", "ADCB", "BACD"], 2, S.p3, E],
    ["2013-ist-034", "istorie", "diplomatie-conflict", "Ordonați cronologic evenimentele: A. Bătălia de la Călugăreni; B. Numirea lui Iancu de Hunedoara în funcția de guvernator al Ungariei; C. Încercarea turcilor de cucerire a Belgradului; D. Începutul domniei lui Mircea cel Bătrân.", ["ADCB", "ACBD", "DBCA", "BACD"], 2, S.p3, E],
    ["2013-ist-035", "istorie", "stat-modern", "Ordonați cronologic evenimentele: A. Constituirea Partidului Conservator; B. Adunarea națională de la Alba Iulia hotărăște unirea Transilvaniei cu România; C. Proclamarea Regatului; D. Sfatul Țării hotărăște unirea Bucovinei cu România.", ["BCDA", "ACDB", "CDBA", "DBAC"], 1, S.p3, "Răspunsul reproduce baremul oficial. Itemul este carantinat: formularea atribuie în mod eronat Sfatului Țării hotărârea unirii Bucovinei cu România."],
    ["2013-ist-036", "istorie", "romania-postbelica", "Ordonați cronologic evenimentele: A. Naționalizarea principalelor mijloace de producție; B. Constituirea guvernului Constantin Sănătescu; C. Abdicarea regelui Mihai; D. Intrarea regelui Mihai în „greva regală”.", ["ACBD", "DBAC", "BDCA", "CADB"], 2, S.p3, E],
    ["2013-ist-037", "istorie", "stat-modern", "Ordonați cronologic evenimentele: A. Formarea primului guvern unic al Principatelor Unite; B. Proclamarea înfăptuirii Unirii depline de către Al. I. Cuza; C. Înființarea Universității de la Iași; D. Elaborarea Legii secularizării averilor mănăstirești.", ["ABCD", "CBAD", "DABC", "BCDA"], 1, S.p3, E],
    ["2013-ist-038", "istorie", "diplomatie-conflict", "Ordonați cronologic evenimentele: A. Înfăptuirea primei uniri politice a Țărilor Române; B. Cucerirea Chiliei și Cetății Albe de către turci; C. Cucerirea Țaratului de Vidin de către Baiazid I; D. Preluarea Dobrogei de către Mircea cel Bătrân.", ["BDCA", "CADB", "BCDA", "DCBA"], 3, S.p3, E],
    ["2013-ist-039", "istorie", "concert-european", "Ordonați cronologic evenimentele: A. Definitivarea alianței franco-anglo-ruse (Tripla Înțelegere sau Antanta); B. Semnarea Tratatului dintre Germania, Austro-Ungaria și Italia prin care se pun bazele primului sistem politico-militar; C. România semnează un tratat secret cu puterile Triplei Alianțe; D. Izbucnește Primul Război Balcanic.", ["BCAD", "ACDB", "CDBA", "DBAC"], 0, S.p3, E],
    ["2013-ist-040", "istorie", "autonomii-institutii", "Ordonați cronologic evenimentele: A. Instaurarea regimului fanariot în Moldova; B. Transformarea Transilvaniei din voievodat în principat; C. Bătălia de la Mohacs; D. Cucerirea Constantinopolului de către turci.", ["BCAD", "ABDC", "CDAB", "DCBA"], 3, S.p3, E],

    ["2013-ist-041", "istorie", "concert-european", "Ordonați cronologic evenimentele: A. Adoptarea Constituției de către Carol al II-lea; B. Încheierea Acordului de la München; C. Izbucnirea celui De-al Doilea Război Mondial; D. Încheierea Pactului Ribbentrop-Molotov.", ["DCAB", "CABD", "ABDC", "BCAD"], 2, S.p4, E],
    ["2013-ist-042", "istorie", "romania-postbelica", "Ordonați cronologic evenimentele: A. Preluarea puterii de către Nicolae Ceaușescu; B. Alegerea lui Nicolae Ceaușescu în funcția de președinte al Consiliului de Stat; C. Naționalizarea principalelor mijloace de producție; D. Începutul colectivizării agriculturii.", ["CDAB", "DBCA", "ACDB", "BACD"], 0, S.p4, E],
    ["2013-ist-043", "istorie", "concert-european", "Ordonați cronologic evenimentele: A. Marea Britanie declară război României, sub presiunea Uniunii Sovietice; B. România declară război Statelor Unite, obligată de Germania; C. Efectivele românești iau parte la ofensiva germană din sudul Rusiei și Caucaz; D. Regele Mihai I și Ion Antonescu proclamă începerea războiului pentru eliberarea Basarabiei și a Bucovinei de nord.", ["ACBD", "BACD", "CDAB", "DBAC"], 3, S.p4, E],
    ["2013-ist-044", "istorie", "romania-postbelica", "Ordonați cronologic evenimentele: A. Alegerea lui Nicolae Ceaușescu în funcția de președinte al Republicii Socialiste România; B. Începutul colectivizării agriculturii; C. Desființarea Academiei Române; D. Retragerea trupelor sovietice din România.", ["BCAD", "DACB", "ADBC", "CBDA"], 3, S.p4, E],
    ["2013-ist-045", "istorie", "concert-european", "Ordonați cronologic evenimentele: A. Adoptarea Constituției prin care se statua rolul conducător al Partidului Comunist Român; B. Renunțarea la garanțiile britanice de către guvernul român, în contextul izbucnirii celui De-al Doilea Război Mondial; C. Încheierea Pactului Briand-Kellogg care reglementa relațiile internaționale; D. Încheierea tratatului economic dintre România și Germania.", ["BDAC", "CDBA", "DBCA", "ABCD"], 1, S.p4, E],
    ["2013-ist-046", "istorie", "romania-postbelica", "Ordonați cronologic evenimentele: A. Abdicarea regelui Mihai; B. Constituirea guvernului Constantin Sănătescu; C. Încercarea Moscovei de impunere a planului Valev; D. Organizarea Direcției Generale a Securității Poporului.", ["BADC", "DCBA", "BCDA", "ADCB"], 0, S.p4, E],
    ["2013-ist-047", "istorie", "stat-modern", "Ordonați cronologic evenimentele: A. Constituirea Partidului Conservator; B. Formarea primului guvern unic al Principatelor Unite; C. Abdicarea lui Al. I. Cuza; D. Elaborarea, la Iași, a Constituției Cărvunarilor.", ["ADBC", "DBCA", "CBAD", "BDCA"], 1, S.p4, E],
    ["2013-ist-048", "istorie", "autonomii-institutii", "Ordonați cronologic evenimentele: A. Transformarea Ungariei în pașalâc; B. Marea invazie tătară în spațiul românesc; C. Așezarea ungurilor în Panonia; D. Excluderea românilor din sistemul națiunilor privilegiate.", ["ADCB", "DBCA", "BADC", "CBDA"], 3, S.p4, E],
    ["2013-ist-049", "istorie", "stat-modern", "Ordonați cronologic evenimentele: A. Recunoașterea oficială a unirii de către puterile garante; B. Formarea guvernului unic condus de Barbu Catargiu; C. Bucureștiul devenea capitala Principatelor Unite; D. Înființarea Casei de Economii și Consemnațiuni din timpul domniei lui Al. I. Cuza.", ["ABCD", "CDAB", "BCAD", "DCAB"], 0, S.p4, E],
    ["2013-ist-050", "istorie", "concert-european", "Ordonați cronologic evenimentele: A. Consiliul de Coroană de la Sinaia hotărăște pentru România adoptarea politicii de neutralitate; B. Moare regele Carol I; C. Semnarea convenției politice și militare care stabileau condițiile intrării României în Primul Război Mondial; D. România declară război Austro-Ungariei.", ["CBDA", "ABCD", "DCBA", "BDCA"], 1, S.p4, E],

    ["2013-ist-051", "istorie", "autonomii-institutii", "Ordonați cronologic evenimentele: A. Prezența în documente a unui Mercurius princeps Ultrasilvanus; B. Întemeierea Mitropoliei de la Curtea de Argeș; C. Transformarea Transilvaniei din voievodat în principat; D. Bătălia de la Rovine.", ["DACB", "ABDC", "CABD", "BDCA"], 1, S.p5, E],
    ["2013-ist-052", "istorie", "stat-modern", "Ordonați cronologic evenimentele: A. Lascăr Catargiu devine lider al Partidului Conservator; B. Proclamarea autocefaliei Bisericii Ortodoxe în raport cu Patriarhia din Constantinopol; C. Introducerea rotativei guvernamentale; D. Bucureștiul devenea capitala Principatelor Unite.", ["ADCB", "BDCA", "CABD", "DABC"], 3, S.p5, E],
    ["2013-ist-053", "istorie", "romania-postbelica", "Ordonați cronologic evenimentele: A. Congresul al IX-lea al Partidului Comunist Român; B. Încheierea colectivizării agriculturii; C. Demonstrația muncitorilor brașoveni; D. Desființarea Academiei Române.", ["DBAC", "ADBC", "CDAB", "BCDA"], 0, S.p5, E],
    ["2013-ist-054", "istorie", "concert-european", "Ordonați cronologic evenimentele: A. Promulgarea reformei rurale de către domnitorul Al. I. Cuza; B. Definitivarea alianței franco-anglo-ruse (Tripla Înțelegere sau Antanta); C. Declanșarea Războiului Crimeii; D. Semnarea de către Rusia a păcii de la Brest-Litovsk.", ["ACDB", "BCAD", "DCAB", "CABD"], 3, S.p5, E],
    ["2013-ist-055", "istorie", "romania-postbelica", "Ordonați cronologic evenimentele: A. Alegerea lui Nicolae Ceaușescu președinte al Republicii Socialiste România; B. Naționalizarea mijloacelor de producție; C. Începutul colectivizării agriculturii; D. Adoptarea Constituției Republicii Socialiste România.", ["DABC", "ACDB", "CADB", "BCDA"], 3, S.p5, E],
    ["2013-ist-056", "istorie", "stat-modern", "Ordonați cronologic evenimentele: A. Proclamarea Regatului; B. Începe guvernarea Principatelor Române prin căimăcămie; C. Dubla alegere a lui Al. I. Cuza, la Iași și la București; D. Elaborarea Statutului dezvoltător al Convenției de la Paris.", ["ABCD", "CDAB", "DACB", "BCDA"], 3, S.p5, E],
    ["2013-ist-057", "istorie", "romania-postbelica", "Ordonați cronologic evenimentele: A. Constituirea guvernului Nicolae Rădescu; B. Adoptarea Constituției Republicii Socialiste România; C. Proclamarea Republicii Populare Române; D. Înființarea Direcției Generale a Miliției.", ["BDAC", "DCAB", "CABD", "ACDB"], 3, S.p5, E],
    ["2013-ist-058", "istorie", "constitutii", "Ordonați cronologic evenimentele: A. Instituirea funcției de președinte al Republicii Socialiste România; B. Adoptarea Constituției care transforma România în republică socialistă; C. Adoptarea Constituției prin care se statua rolul conducător al Partidului Muncitoresc Român; D. Adoptarea Constituției prin care societatea românească revenea la democrație.", ["ABCD", "BCAD", "CBAD", "DABC"], 2, S.p5, E],
    ["2013-ist-059", "istorie", "romania-postbelica", "Ordonați cronologic evenimentele: A. Organizarea Direcției Generale a Securității Poporului; B. Intrarea regelui Mihai în „greva regală”; C. Ieșirea României din război împotriva Națiunilor Unite; D. Reintroducerea cartelelor de alimente.", ["CBAD", "ADCB", "DBCA", "BACD"], 0, S.p5, E],
    ["2013-ist-060", "istorie", "stat-modern", "Ordonați cronologic evenimentele: A. Promulgarea primei Constituții interne românești; B. Adunarea Națională de la Alba Iulia hotărăște unirea Transilvaniei cu România; C. Elaborarea Legii instrucțiunii publice din timpul domniei lui Al. I. Cuza; D. Abdicarea lui Al. I. Cuza.", ["BCDA", "ADCB", "CDAB", "DCAB"], 2, S.p5, E]
  ]);
})();
