(() => {
  'use strict';
  const S = {
    p1: "SNPAP Târgu Ocna – Admitere 2020, Istoria românilor, Varianta III, barem oficial, p. 1.",
    p2: "SNPAP Târgu Ocna – Admitere 2020, Istoria românilor, Varianta III, barem oficial, p. 2.",
    p3: "SNPAP Târgu Ocna – Admitere 2020, Istoria românilor, Varianta III, barem oficial, p. 3.",
    key: "SNPAP Târgu Ocna – Admitere 2020, Istoria românilor, grila oficială de răspuns, p. 4."
  };
  const E = "Răspuns verificat în baremul oficial și în grila oficială de răspuns.";
  window.registerQuestionBatch([
    ["2020-ist-001", "istorie", "stat-modern", "Palatul Parlamentului din București a fost construit la începutul anilor:", ["1900", "2000", "1800", "1990"], 0, S.p1, E],
    ["2020-ist-002", "istorie", "constitutii", "La articolul 1 din Constituția de la 1923, Regatul României era:", ["stat național, unitar și indivizibil", "stat independent", "stat nealienabil", "stat vasal"], 0, S.p1, E],
    ["2020-ist-003", "istorie", "constitutii", "La articolul 19 din Constituția de la 1923, se făcea referire la:", ["bogățiile subsolului sunt declarate proprietate de stat", "căile de comunicație, apele navigabile și flotabile, sunt incluse în domeniul public", "asigurarea socială a muncitorilor în caz de accident", "statutul aparte al Bisericii Greco-Catolice, privilegiată în raport cu alte culte"], 0, S.p1, E],
    ["2020-ist-004", "istorie", "autonomii-institutii", "Basarab se recunoștea vasal al regelui Carol Robert de Anjou în anul:", ["1290", "1300", "1324", "1330"], 2, S.p1, E],
    ["2020-ist-005", "istorie", "autonomii-institutii", "În 1359, Nicolae Alexandru își ia titlul de:", ["mitropolit", "singur stăpânitor", "logofăt", "dominus"], 1, S.p1, E],
    ["2020-ist-006", "istorie", "autonomii-institutii", "O marcă de apărare a fost creată în nordul Moldovei din inițiativa regelui maghiar, fiind condusă de:", ["Sas", "Balc", "Dragoș", "Bogdan"], 2, S.p1, E],
    ["2020-ist-007", "istorie", "stat-modern", "Conform Convenției de la Paris, puterea legislativă se exercita colectiv de către:", ["domn, guvern și Înalta Curte de Justiție și Casație", "domn, guvern și Comisia Centrală de la Focșani", "domn, Adunare și Comisia Centrală de la Focșani", "domn, guvern și Adunare"], 2, S.p1, E],
    ["2020-ist-008", "istorie", "stat-modern", "Corpul Ponderator a fost introdus prin:", ["Convenția de la Paris", "Statutul Dezvoltător al Convenției de la Paris", "Codul Civil", "Constituția din 1866"], 1, S.p1, E],
    ["2020-ist-009", "istorie", "stat-modern", "La baza înființării PNL a stat:", ["Coaliția de la Mazar Pașa", "gruparea junimistă", "teoria formelor fără fond", "teoria pașilor mărunți"], 0, S.p1, E],
    ["2020-ist-010", "istorie", "diplomatie-conflict", "Informații despre expediția otomană din 1462 împotriva lui Vlad Țepeș sunt oferite de:", ["Istoria turco-bizantină", "Expuneri istorice", "Alexiada", "Scrisoarea circulară"], 0, S.p1, E],
    ["2020-ist-011", "istorie", "diplomatie-conflict", "Iancu de Hunedoara a obținut o importantă victorie pe râul Ialomița și îl impune apoi ca domn în Țara Românească pe:", ["Vlad Țepeș", "Vlad Dracul", "Vladislav Vlaicu", "Vladislav I"], 1, S.p1, E],
    ["2020-ist-012", "istorie", "diplomatie-conflict", "Ștefan cel Mare a ocupat tronul Moldovei cu sprijinul lui:", ["Vlad Țepeș", "Vlad Dracul", "Radu cel Frumos", "Iancu de Hunedoara"], 0, S.p1, E],
    ["2020-ist-013", "istorie", "constitutii", "La articolul 22 din Constituția de la 1923, se făcea referire la:", ["bogățiile subsolului sunt declarate proprietate de stat", "căile de comunicație, apele navigabile și flotabile, sunt incluse în domeniul public", "asigurarea socială a muncitorilor în caz de accident", "statutul aparte al Bisericii Greco-Catolice, privilegiată în raport cu alte culte"], 3, S.p1, E],
    ["2020-ist-014", "istorie", "autonomii-institutii", "Legea clerului mirean și a seminariilor prevedea:", ["unirea bisericii Greco-Catolice", "salarizarea preoților din bugetul statului sau al localităților", "salarizarea preoților din bugetul Patriarhiei din Constantinopol", "unirea Bisericii Ortodoxe cu Roma"], 1, S.p1, E],
    ["2020-ist-015", "istorie", "autonomii-institutii", "Regele Ludovic I a condiționat calitatea de nobil de apartenența la catolicism în anul:", ["1247", "1366", "1330", "1359"], 1, S.p2, E],
    ["2020-ist-016", "istorie", "diplomatie-conflict", "Mihai Viteazul obținea din partea Imperiului Otoman recunoașterea domniei pe viață în anul:", ["1593", "1595", "1597", "1598"], 2, S.p2, E],
    ["2020-ist-017", "istorie", "concert-european", "Un atac general asupra Plevnei s-a declanșat la data de:", ["28 noiembrie 1877", "30 august 1877", "9 noiembrie 1877", "19 februarie 1878"], 1, S.p2, E],
    ["2020-ist-018", "istorie", "concert-european", "Discuția dintre primul ministru, I.C. Brătianu, și țarul Rusiei, Alexandru al II-lea, a avut loc la:", ["Berlin", "Livadia", "Paris", "San Stefano"], 1, S.p2, E],
    ["2020-ist-019", "istorie", "concert-european", "Revizuiește Tratatul de la San Stefano, pentru a micșora influența Rusiei în Europa de sud-est:", ["Congresul de la Paris", "Congresul de la Adrianopol", "Congresul de la Berlin", "Congresul de la Londra"], 2, S.p2, E],
    ["2020-ist-020", "istorie", "concert-european", "Recunoașterea independenței României, cu două condiții, a fost prevăzută în Tratatul de la:", ["Paris", "Adrianopol", "Akkerman", "Berlin"], 3, S.p2, E],
    ["2020-ist-021", "istorie", "constitutii", "Ordonați cronologic constituțiile: A. Constituția care preciza la articolul 82: „puterile constituționale ale domnului sunt ereditare”; B. Constituția care preciza la articolul 39 „puterea executivă este încredințată Regelui, care o exercită în modul reglementat prin Constituție”; C. Constituția care preciza, la articolul 45: „Regele este capul oștirii”; D. Constituția care preciza, la articolul 2: „Întreaga putere în Republica Socialistă România aparține poporului.”", ["CBDA", "ABCD", "CABD", "ACBD"], 1, S.p2, E],
    ["2020-ist-022", "istorie", "constitutii", "Ordonați cronologic constituțiile: A. Constituția aprobată prin referendum; B. Constituția aprobată prin plebiscit; C. Constituția construirii socialismului; D. Constituția cărvunarilor.", ["DCBA", "ABCD", "DBCA", "BCAD"], 2, S.p2, E],
    ["2020-ist-023", "istorie", "stat-modern", "Ordonați cronologic evenimentele: A. Lovitura de stat a lui Al. I. Cuza; B. Statutul Dezvoltător al Convenției de la Paris; C. Revenirea la județe, ca formă de administrare locală; D. Modificarea primei constituții democratice postbelice.", ["CBDA", "ABCD", "ACBD", "BCAD"], 1, S.p2, E],
    ["2020-ist-024", "istorie", "autonomii-institutii", "Ordonați cronologic evenimentele: A. Cluj, Alba, Timiș devin comitate; B. Bihorul devine comitat; C. Crasna și Dăbâca devin comitate; D. Este organizată Mitropolia Ungrovlahiei.", ["BACD", "BCAD", "ACBD", "ABDC"], 1, S.p2, E],
    ["2020-ist-025", "istorie", "autonomii-institutii", "Ordonați cronologic evenimentele: A. Transilvania este organizată ca voievodat în cadrul regatului Ungariei; B. Transilvania devine principat autonom sub suzeranitate otomană; C. Instalarea stăpânirii habsburgice în Transilvania; D. Instalarea regimului fanariot în Țara Românească.", ["ADBC", "CABD", "ACBD", "ABCD"], 3, S.p2, E],
    ["2020-ist-026", "istorie", "autonomii-institutii", "Ordonați cronologic evenimentele: A. Organizarea Guberniului ca instituție administrativă în timpul dominației habsburgice; B. Ultima Adunare a țării dedicată desființării șerbiei; C. Vladislav Vlaicu întemeiază Mitropolia de la Severin; D. Mitropolia ortodoxă de la Suceava este recunoscută de către Bizanț.", ["DACB", "CDAB", "ABCD", "CADB"], 1, S.p2, E],
    ["2020-ist-027", "istorie", "stat-modern", "Ordonați cronologic evenimentele: A. 463.554 familii de țărani au primit 18.180.311 ha de pământ; B. Legea care reglementa instruirea la toate nivelurile, acordând o atenție particulară învățământului primar; C. Înființarea Casei de Economii și Consemnațiuni; D. Înțelegerea de la Hotelul Concordia.", ["ACBD", "ABCD", "CABD", "BCAD"], 1, S.p2, E],
    ["2020-ist-028", "istorie", "stat-modern", "Ordonați cronologic evenimentele: A. Petre P. Carp prezintă câteva idei care vizau și elaborarea unor măsuri în favoarea țăranilor și meseriașilor; B. Se încheie prima guvernare liberală; C. Se încheie ultima guvernare conservatoare; D. Program elaborat de Congresul PNL care se pronunța pentru desfășurarea alegerilor în mod liber, măsuri pentru îmbunătățirea situației țăranilor.", ["CBDA", "BADC", "DBCA", "BDAC"], 3, S.p2, E],
    ["2020-ist-029", "istorie", "stat-modern", "Ordonați cronologic evenimentele: A. Lui Carol de Hohenzollern i se acordă titlul de Alteță Regală; B. Carol primește firman de numire din partea sultanului; C. Este impusă rotativa guvernamentală; D. România devine regat.", ["BDAC", "ACDB", "CABD", "BADC"], 3, S.p2, E],
    ["2020-ist-030", "istorie", "diplomatie-conflict", "Ordonați cronologic evenimentele: A. Lupta de la Baia; B. Ștefan cel Mare aduce sub stăpânirea sa cetatea Chilia; C. Tratatul de la Hârlău; D. Moldova plătește pentru prima dată tribut turcilor.", ["BADC", "ADCB", "DBAC", "DCAB"], 2, S.p2, E],
    ["2020-ist-031", "istorie", "diplomatie-conflict", "Ordonați cronologic evenimentele: A. A treia domnie a lui Vlad Țepeș; B. Iancu de Hunedoara înfrânge o oaste otomană intrată în Transilvania; C. Lupta de la Belgrad; D. Campania lui Mehmed al II-lea în Țara Românească.", ["BACD", "CBDA", "DCBA", "BCDA"], 3, S.p3, E],
    ["2020-ist-032", "istorie", "diplomatie-conflict", "Ordonați cronologic evenimentele: A. Mircea cel Bătrân intervine în favoarea sârbilor; B. Baiazid I a cucerit țaratul de Vidin; C. Răscoala antiotomană a lui Mihai Viteazul de la București; D. Turcii ocupă țaratul de Târnovo.", ["ADBC", "ABCD", "DACB", "DCBA"], 0, S.p3, E],
    ["2020-ist-033", "istorie", "constitutii", "Ordonați cronologic constituțiile: A. Constituția care impunea Parlamentului rol corporativ; B. Constituția care preciza egalitatea între sexe, fără a da drept de vot femeilor; C. Constituția care statua rolul conducător al PCR; D. Prima constituție care prevedea dreptul deputaților de a interpela guvernul.", ["DABC", "DBAC", "CABD", "BCAD"], 1, S.p3, E],
    ["2020-ist-034", "istorie", "stat-modern", "Ordonați cronologic evenimentele: A. Se constituie Partidul Național Moldovenesc; B. Congresul ostașilor moldoveni proclamă autonomia Basarabiei; C. Se constituie Sfatul Țării; D. Este proclamată Republica Democratică Moldovenească.", ["CBDA", "ABCD", "ACBD", "CDBA"], 1, S.p3, E],
    ["2020-ist-035", "istorie", "autonomii-institutii", "Ordonați cronologic domniile: A. Domnia lui Basarab; B. Domnia lui Mircea cel Bătrân; C. Domnia lui Lațcu; D. Domnia lui Ioan Asan al II-lea.", ["ABCD", "BADC", "DBCA", "DACB"], 3, S.p3, E],
    ["2020-ist-036", "istorie", "diplomatie-conflict", "Ordonați cronologic evenimentele: A. Regele Ungariei, Vladislav I a căzut pe câmpul de luptă; B. Iancu de Hunedoara a fost numit guvernator al Ungariei; C. Ioan Albert devine rege al Poloniei; D. Mihai Viteazul semnează un tratat cu împăratul Rudolf al II-lea.", ["ACBD", "ADCB", "ABDC", "ABCD"], 3, S.p3, E],
    ["2020-ist-037", "istorie", "romania-postbelica", "Ordonați cronologic evenimentele: A. Arbitrajul de la Viena; B. Notele ultimative adresate de Moscova guvernului român; C. Vizita lui Ion Antonescu în Germania; D. Tratatul de la Craiova.", ["BADC", "ABDC", "BDAC", "ADCB"], 0, S.p3, E],
    ["2020-ist-038", "istorie", "romania-postbelica", "Ordonați cronologic evenimentele: A. Carol al II-lea abdică în favoarea fiului său Mihai; B. România a intrat în război alături de Germania; C. România a aderat la Pactul Tripartit; D. Carol al II-lea a adus la putere un cabinet progerman condus de Ion Gigurtu.", ["ADCB", "DACB", "DCAB", "ACDB"], 1, S.p3, E],
    ["2020-ist-039", "istorie", "concert-european", "Ordonați cronologic evenimentele: A. România se alătură coaliției Națiunilor Unite; B. România a semnat tratatul de pace cu Națiunile Unite; C. Înțelegerea Balcanică; D. Mica Înțelegere.", ["DACB", "ABCD", "DCAB", "ADCB"], 2, S.p3, E],
    ["2020-ist-040", "istorie", "concert-european", "Ordonați cronologic evenimentele: A. Ultimul asediu al Vienei organizat de turci; B. Tratatul de la Kuciuk-Kainargi; C. Oltenia a fost ocupată de Habsburgi; D. Austria anexează Bucovina.", ["ABCD", "ABDC", "CABD", "ACBD"], 3, S.p3, E]
  ]);
})();
