(() => {
  'use strict';
  const S = {
    hi1: "SNPAP Târgu Ocna – Admitere 2021, Istoria românilor, Varianta I, Barem de corectare, p. 1.",
    hi2: "SNPAP Târgu Ocna – Admitere 2021, Istoria românilor, Varianta I, Barem de corectare, p. 2.",
    hi3: "SNPAP Târgu Ocna – Admitere 2021, Istoria românilor, Varianta I, grila oficială de răspuns, p. 3."
  };
  const E = "Răspuns conform baremului oficial publicat de SNPAP Târgu Ocna; grila de răspuns de la p. 3 confirmă cheia.";
  window.registerQuestionBatch([
    ["2021-ist-001", "istorie", "autonomii-institutii", "Mitropolia Țării Românești a fost inaugurată în:", ["mai 1359", "iunie 1359", "martie 1359", "august 1359"], 0, S.hi1, E],
    ["2021-ist-002", "istorie", "autonomii-institutii", "Anonymus îl numea pe Gelu:", ["valah", "voloh", "olah", "blach"], 3, S.hi1, E],
    ["2021-ist-003", "istorie", "diplomatie-conflict", "Tipul de război purtat de Țările Române cu otomanii în Evul Mediu, ar putea fi caracterizat drept:", ["conflict ocazional", "conflict permanent", "conflict asimetric", "conflict simetric"], 2, S.hi1, E],
    ["2021-ist-004", "istorie", "diplomatie-conflict", "Provincia turcească aflată sub guvernarea unui pașă era denumită:", ["beglerbeg", "eylat", "principat", "comitat"], 1, S.hi1, E],
    ["2021-ist-005", "istorie", "stat-modern", "Carol I a primit titlul de Rege al României în anul:", ["1866", "1878", "1881", "1884"], 2, S.hi1, E],
    ["2021-ist-006", "istorie", "diplomatie-conflict", "Ioan Albert devine rege al Poloniei în anul:", ["1490", "1491", "1492", "1494"], 2, S.hi1, E],
    ["2021-ist-007", "istorie", "stat-modern", "Alexandru Ioan Cuza a impus un nou act constituțional prin lovitura de stat din 1864 numit:", ["Constituția Cărvunarilor", "Regulamentele Organice", "Convenția de la Paris", "Statutul Dezvoltător al Convenției de la Paris"], 3, S.hi1, E],
    ["2021-ist-008", "istorie", "stat-modern", "Înființarea Partidului Național Liberal s-a realizat în urma unei înțelegeri cunoscute sub numele:", ["Programul de la Concordia", "Coaliția de la Mazar-Pașa", "Monstruoasa Coaliție", "Teoria formelor fără fond"], 1, S.hi1, E],
    ["2021-ist-009", "istorie", "constitutii", "Constituția din 1923 a fost promulgată la data de:", ["25 martie", "27 martie", "28 martie", "30 martie"], 2, S.hi1, E],
    ["2021-ist-010", "istorie", "constitutii", "„Art. 1. Regatul României este un stat național, unitar și indivizibil” este o prevedere a Constituției din:", ["1866", "1923", "1938", "1948"], 1, S.hi1, E],
    ["2021-ist-011", "istorie", "concert-european", "Congresul de la Paris care a pus capăt Războiului Crimeii a avut loc în anul:", ["1856", "1857", "1858", "1859"], 0, S.hi1, E],
    ["2021-ist-012", "istorie", "romania-postbelica", "Fenomenul deportărilor, caracteristic represiunii comuniste, a început în:", ["1946", "1948", "1951", "1964"], 2, S.hi1, E],
    ["2021-ist-013", "istorie", "concert-european", "România aderă la Tripla Alianță în anul:", ["1883", "1882", "1881", "1913"], 0, S.hi1, E],
    ["2021-ist-014", "istorie", "romania-postbelica", "Nicolae Ceaușescu a fost ales președinte al Consiliului de Stat în anul:", ["1965", "1967", "1968", "1974"], 1, S.hi1, E],
    ["2021-ist-015", "istorie", "romania-postbelica", "Instalarea unui guvern procomunist condus de Petru Groza a avut loc în data de:", ["23 august 1944", "6 decembrie 1944", "6 martie 1945", "23 august 1945"], 2, S.hi2, E],
    ["2021-ist-016", "istorie", "autonomii-institutii", "Ordonați cronologic evenimentele: A. Menționarea documentară a lui Mercurius princeps Ultrasilvanus; B. Menționarea documentară a lui Leustachius voievod; C. Condiționarea calității de nobil în Transilvania, de apartenența la religia catolică; D. Elaborarea Diplomei prin care Transilvania devine o provincie a Imperiului Habsburgic.", ["ACDB", "CABD", "BDAC", "ABCD"], 3, S.hi2, E],
    ["2021-ist-017", "istorie", "autonomii-institutii", "Ordonați cronologic evenimentele: A. „Puternicii acelor locuri” sunt atestați într-un document al cancelariei papale; B. Începutul domniei lui Roman I; C. Începutul domniei lui Ivanco; D. Nicolae Alexandru ia titlul de samodirjeț.", ["ACBD", "ADCB", "CABD", "BCAD"], 1, S.hi2, E],
    ["2021-ist-018", "istorie", "diplomatie-conflict", "Ordonați cronologic evenimentele: A. Albert Kiraly oferă sprijin militar lui Mihai Viteazul; B. Are loc Cruciada de la Varna; C. Are loc Cruciada de la Nicopole; D. Vlad Țepeș este înscăunat de Iancu de Hunedoara.", ["CDBA", "ABCD", "BCDA", "CBDA"], 3, S.hi2, E],
    ["2021-ist-019", "istorie", "diplomatie-conflict", "Ordonați cronologic evenimentele: A. Pacea de la Seghedin; B. Bătălia de la Vaslui; C. Cruciada de la Nicopole; D. Bătălia de la Războieni.", ["CABD", "CBDA", "BDCA", "ABCD"], 0, S.hi2, E],
    ["2021-ist-020", "istorie", "concert-european", "Ordonați cronologic evenimentele: A. România semnează Tratatul de la București prin care devenea dependentă de Puterile Centrale; B. România a adoptat poziția de neutralitate față de Primul Război Mondial; C. România a semnat convențiile politice și militare ce stabileau condițiile intrării în Primul Război Mondial; D. Luptele de la Mărăști, Mărășești, Oituz.", ["ABCD", "BACD", "BCDA", "DBAC"], 2, S.hi2, E],
    ["2021-ist-021", "istorie", "stat-modern", "Ordonați cronologic evenimentele: A. Biserica Ortodoxă își proclama autocefalia; B. Legea secularizării pământurilor mănăstirești; C. Tratatul secret semnat de România cu Austro-Ungaria; D. Pacea de la Brest-Litovsk.", ["BACD", "BCAD", "CBAD", "CBDA"], 1, S.hi2, E],
    ["2021-ist-022", "istorie", "stat-modern", "Ordonați cronologic actele: A. Statutul Dezvoltător al Convenției de la Paris; B. Constituția Cărvunarilor; C. Convenția de la Paris; D. Constituția care inaugurează regimul monarhiei constituționale.", ["BDAC", "BACD", "BCAD", "ABDC"], 2, S.hi2, E],
    ["2021-ist-023", "istorie", "romania-postbelica", "Ordonați cronologic evenimentele: A. Căderea regimului comunist în România; B. Înființarea funcției de președinte al României; C. Constituția care prevedea că România devenea o monarhie autoritară; D. Constituția care statua rolul conducător al Partidului Comunist Român în întreaga viață a societății.", ["ABCD", "CDBA", "BDAC", "CDAB"], 1, S.hi2, E],
    ["2021-ist-024", "istorie", "concert-european", "Ordonați cronologic evenimentele: A. Armatele româno-ruse declanșează atacul asupra Plevnei; B. Se desfășoară Congresul de pace de la Berlin; C. Începe Primul Război Mondial; D. România este proclamată Regat.", ["ABCD", "BCDA", "ABDC", "DABC"], 2, S.hi2, E],
    ["2021-ist-025", "istorie", "concert-european", "Ordonați cronologic evenimentele: A. Românii cuceresc reduta Rahova; B. Ion C. Brătianu se întâlnește la Livadia cu țarul Rusiei; C. Se semnează Tratatul de la Adrianopol; D. Se semnează Tratatul de la Kuciuk-Kainargi.", ["ABCD", "BCDA", "CBAD", "DCBA"], 3, S.hi2, E],
    ["2021-ist-026", "istorie", "romania-postbelica", "Ordonați cronologic evenimentele: A. Abdicarea regelui Mihai I; B. Diversiunea de la Tămădău; C. Gheorghe Gheorghiu-Dej devine președinte al Consiliului de Miniștri; D. Declarația din aprilie.", ["ACDB", "BADC", "BACD", "ADBC"], 2, S.hi2, E],
    ["2021-ist-027", "istorie", "romania-postbelica", "Ordonați cronologic evenimentele: A. Publicarea Istoriei României de către M. Roller; B. Întemeierea editurii și a librăriei Cartea Rusă; C. Retragerea trupelor sovietice din România; D. Acordul de la Helsinki.", ["BACD", "BADC", "ABCD", "ABDC"], 0, S.hi2, E],
    ["2021-ist-028", "istorie", "romania-postbelica", "Ordonați cronologic evenimentele: A. Ceaușescu condamnă intervenția în Cehoslovacia; B. Iuliu Maniu moare în penitenciarul de la Sighet; C. Blocul Partidelor Democratice câștigă prin fraudă alegerile parlamentare; D. Regele Mihai I intră în greva regală.", ["CDAB", "DCBA", "CBAD", "DACB"], 1, S.hi2, E],
    ["2021-ist-029", "istorie", "romania-postbelica", "Ordonați cronologic evenimentele: A. Primul plan cincinal; B. Declanșarea procesului de colectivizare a agriculturii; C. Scrisoarea redactată de 6 foști activiști ai PCR; D. Tezele din iulie.", ["BDAC", "BADC", "CBAD", "DACB"], 1, S.hi2, E],
    ["2021-ist-030", "istorie", "romania-postbelica", "Ordonați cronologic evenimentele: A. Eliberarea ultimilor deținuți politici în România; B. Revolta minerilor din Valea Jiului; C. Înființarea Consiliului Economic și de Ajutor Reciproc; D. Plenara CC al PCR care hotărăște reabilitarea victimelor terorii staliniste din timpul lui Gheorghe Gheorghiu-Dej.", ["CADB", "CDAB", "CBAD", "CDAB"], 0, S.hi2, E]
  ]);
})();
