(() => {
  'use strict';
  const S = {
    hi1: "SNPAP Târgu Ocna – Admitere 2022, Istoria românilor, Varianta II, Barem de corectare, p. 1.",
    hi2: "SNPAP Târgu Ocna – Admitere 2022, Istoria românilor, Varianta II, Barem de corectare, p. 2.",
    hi3: "SNPAP Târgu Ocna – Admitere 2022, Istoria românilor, Varianta II, Barem de corectare, p. 3."
  };
  window.registerQuestionBatch([
    ["2022-ist-001", "istorie", "constitutii", "Constituția din 21 noiembrie 1991 a fost adoptată de:", ["Adunarea Constituantă", "Parlament", "Senat", "Camera Deputaților"], 0, S.hi1, "Răspuns conform baremului oficial publicat de SNPAP Târgu Ocna."],
    ["2022-ist-002", "istorie", "constitutii", "Articolele 2 și 3 din Constituția de la 1866 vorbeau despre:", ["inviolabilitatea teritoriului statului, care nu putea fi modificat decât în virtutea unei legi", "atribuțiile domnitorului", "puterile constituționale ale domnitorului", "garantarea libertății individuale"], 0, S.hi1, "Răspuns conform baremului oficial publicat de SNPAP Târgu Ocna."],
    ["2022-ist-003", "istorie", "constitutii", "Statua egalitatea în fața legii pentru toți cetățenii Republicii Populare Române:", ["Constituția din 1948", "Constituția din 1965", "Constituția din 1923", "Constituția din 1991"], 0, S.hi1, "Răspuns conform baremului oficial publicat de SNPAP Târgu Ocna."],
    ["2022-ist-004", "istorie", "autonomii-institutii", "Inscripțiile din complexul Basarabi-Murfatlar atestă formațiunea condusă de:", ["Seslav", "Satza", "Dimitrie", "Gheorghe"], 3, S.hi1, "Răspuns conform baremului oficial publicat de SNPAP Târgu Ocna."],
    ["2022-ist-005", "istorie", "autonomii-institutii", "În timpul răscoalei conduse de frații Petru și Asan, împărat al Imperiului Bizantin era:", ["Isaac al II-lea Angelos", "Alexios Comnenul", "Constantin al VII-lea Porfirogenetul", "Manuel Comnenul"], 0, S.hi1, "Răspuns conform baremului oficial publicat de SNPAP Târgu Ocna."],
    ["2022-ist-006", "istorie", "autonomii-institutii", "În spațiul românesc, în Evul Mediu, așezările rurale risipite în cuprinsul unor țări erau conduse de cnezi și juzi cu funcții:", ["judecătorești sau administrative", "politice sau militare", "politice sau administrative", "judecătorești sau ecleziastice"], 0, S.hi1, "Răspuns conform baremului oficial publicat de SNPAP Târgu Ocna."],
    ["2022-ist-007", "istorie", "stat-modern", "Societatea secretă Eteria avea ca scop eliberarea grecilor, cu sprijinul:", ["României", "Rusiei", "Austriei", "Turciei"], 1, S.hi1, "Răspuns conform baremului oficial publicat de SNPAP Târgu Ocna."],
    ["2022-ist-008", "istorie", "concert-european", "Tratatul de la Adrianopol instituia oficial în Țările Române:", ["suzeranitatea otomană", "garanția colectivă a Marilor Puteri", "protectoratul rusesc", "suzeranitatea maghiară"], 2, S.hi1, "Răspuns conform baremului oficial publicat de SNPAP Târgu Ocna."],
    ["2022-ist-009", "istorie", "stat-modern", "După înfrângerea revoluției de la 1848-1849, în Principatele Române a fost reintrodus:", ["regimul politic autoritar", "regimul politic regulamentar", "regimul politic radical", "regimul politic autocrat"], 1, S.hi1, "Răspuns conform baremului oficial publicat de SNPAP Târgu Ocna."],
    ["2022-ist-010", "istorie", "romania-postbelica", "Prin fraudare, alegerile din 19 noiembrie 1946 au fost câștigate de:", ["Frontul Național Democrat", "Frontul Salvării Naționale", "Alianța condusă de PCR", "Partidul Național Țărănesc"], 2, S.hi1, "Răspuns conform baremului oficial publicat de SNPAP Târgu Ocna."],
    ["2022-ist-011", "istorie", "concert-european", "La 9 februarie 1929 România semna un protocol asemănător cu Pactul Briand-Kellogg, împreună cu:", ["ceilalți vecini ai Franței", "ceilalți vecini ai URSS", "ceilalți vecini ai Ungariei", "ceilalți vecini ai Germaniei"], 1, S.hi1, "Răspuns conform baremului oficial publicat de SNPAP Târgu Ocna."],
    ["2022-ist-012", "istorie", "diplomatie-conflict", "Campania cea lungă a fost o expediție antiotomană organizată:", ["la est de Carpați", "la sud de Balcani", "la est de Nistru", "la vest de Tisa"], 1, S.hi1, "Răspuns conform baremului oficial publicat de SNPAP Târgu Ocna."],
    ["2022-ist-013", "istorie", "autonomii-institutii", "Mircea cel Bătrân a domnit între anii:", ["1387-1416", "1386-1418", "1386-1416", "1387-1418"], 1, S.hi1, "Răspuns conform baremului oficial publicat de SNPAP Târgu Ocna."],
    ["2022-ist-014", "istorie", "romania-postbelica", "Prin Legea nr. 119 din 11 iunie 1948 s-a introdus:", ["colectivizarea agriculturii", "reforma agrară", "naționalizarea principalelor mijloace de producție", "Planul Valev"], 2, S.hi1, "Răspuns conform baremului oficial publicat de SNPAP Târgu Ocna."],
    ["2022-ist-015", "istorie", "concert-european", "Convențiile politice și militare între România și Polonia au fost semnate în 1921, din inițiativa lui:", ["Ion C. Brătianu", "Take Ionescu", "Nicolae Titulescu", "Ion Gigurtu"], 1, S.hi2, "Răspuns conform baremului oficial publicat de SNPAP Târgu Ocna."],
    ["2022-ist-016", "istorie", "stat-modern", "Ordonați cronologic evenimentele: A. Adoptarea Constituției care avea ca model Constituția belgiană; B. Alegerea lui Alexandru Ioan Cuza ca domn al Moldovei; C. Semnarea Convenției de la Paris; D. Înființarea Casei de Economii și Consemnațiuni.", ["ACDB", "CBDA", "DABC", "ABCD"], 1, S.hi2, "Răspuns conform baremului oficial publicat de SNPAP Târgu Ocna."],
    ["2022-ist-017", "istorie", "stat-modern", "Ordonați cronologic evenimentele: A. Sfârșitul Războiului Crimeii; B. Elaborarea Rezoluțiilor Adunărilor ad-hoc; C. Alegerea lui Alexandru Ioan Cuza ca domn al Țării Românești; D. Încheierea Convenției de la Balta Liman.", ["ABCD", "CDAB", "DABC", "ACDB"], 2, S.hi2, "Răspuns conform baremului oficial publicat de SNPAP Târgu Ocna."],
    ["2022-ist-018", "istorie", "stat-modern", "Ordonați cronologic evenimentele: A. Formarea guvernului condus de Barbu Catargiu; B. Promulgarea Statutului Dezvoltător al Convenției de la Paris; C. Elaborarea unor rezoluții prin care se cerea unirea Moldovei cu Țara Românească; D. Semnarea Convenției de la Paris.", ["ABCD", "CDAB", "DABC", "CDBA"], 1, S.hi2, "Răspuns conform baremului oficial publicat de SNPAP Târgu Ocna."],
    ["2022-ist-019", "istorie", "autonomii-institutii", "Ordonați cronologic evenimentele: A. Petru I Mușat depune jurământul de vasalitate regelui Poloniei, Vladislav I Jagiello; B. Nicolae Alexandru își ia titlul de „singur stăpânitor”; C. Prăbușirea Ungariei ca urmare a luptei de la Mohács; D. Adoptarea Diplomei Leopoldine prin care Transilvania devine provincie a Imperiului Habsburgic.", ["ABCD", "CDAB", "BACD", "ACDB"], 2, S.hi2, "Răspuns conform baremului oficial publicat de SNPAP Târgu Ocna."],
    ["2022-ist-020", "istorie", "autonomii-institutii", "Ordonați cronologic evenimentele: A. Menționarea Țării Cărvunei; B. Întemeierea Themei Paristrion; C. Revenirea în Transilvania la instituția voievodatului; D. Atestarea formațiunii conduse de jupan Dimitrie.", ["ABCD", "CDAB", "DBCA", "ACDB"], 2, S.hi2, "Răspuns conform baremului oficial publicat de SNPAP Târgu Ocna."],
    ["2022-ist-021", "istorie", "autonomii-institutii", "Ordonați cronologic evenimentele: A. Nicolae Alexandru devine samodirjeț; B. Începutul domniei lui Vladislav Vlaicu; C. Sfârșitul domniei lui Dobrotici; D. Sfârșitul domniei lui Roman I.", ["ADCB", "CDAB", "DABC", "ABCD"], 3, S.hi2, "Răspuns conform baremului oficial publicat de SNPAP Târgu Ocna."],
    ["2022-ist-022", "istorie", "stat-modern", "Ordonați cronologic evenimentele: A. Statutul Dezvoltător al Convenției de la Paris; B. Proclamarea României ca regat; C. Înțelegerea de la Concordia; D. Constituirea Partidului Conservator.", ["DBCA", "CDAB", "ACDB", "ACBD"], 2, S.hi2, "Răspuns conform baremului oficial publicat de SNPAP Târgu Ocna."],
    ["2022-ist-023", "istorie", "stat-modern", "Ordonați cronologic evenimentele: A. Parlamentul României votează legile de ratificare a unirii Basarabiei, Bucovinei și Transilvaniei cu România; B. Are loc încoronarea regelui Ferdinand I și a reginei Maria la Alba Iulia; C. România este proclamată regat; D. Este adoptată Constituția care consfințește Unirea.", ["DBCA", "CABD", "DABC", "ACBD"], 1, S.hi2, "Răspuns conform baremului oficial publicat de SNPAP Târgu Ocna."],
    ["2022-ist-024", "istorie", "stat-modern", "Ordonați cronologic evenimentele: A. Principele Carol realizează o vizită la Istanbul, în timpul căreia primește firmanul de numire; B. Acordarea titlului de „Alteță regală” prințului Carol; C. Declanșarea războaielor balcanice; D. Introducerea rotativei guvernamentale.", ["DBCA", "CDAB", "ABDC", "ACBD"], 2, S.hi2, "Răspuns conform baremului oficial publicat de SNPAP Târgu Ocna."],
    ["2022-ist-025", "istorie", "romania-postbelica", "Ordonați cronologic evenimentele: A. Începutul deportărilor din Banat în Bărăgan; B. Organizarea primelor nuclee de luptă anticomunistă din munți; C. Declarația din aprilie a PMR; D. Nicolae Ceaușescu devine primul președinte al României.", ["BACD", "ABDC", "CABD", "ABCD"], 0, S.hi2, "Răspuns conform baremului oficial publicat de SNPAP Târgu Ocna."],
    ["2022-ist-026", "istorie", "romania-postbelica", "Ordonați cronologic evenimentele: A. Manifestația muncitorilor de la uzina Steagul Roșu din Brașov; B. Decretele de eliberare a ultimilor 10 410 deținuți politici; C. Retragerea trupelor sovietice din România; D. Revolta minerilor din Valea Jiului.", ["CBDA", "BDCA", "DCAB", "ACBD"], 0, S.hi2, "Răspuns conform baremului oficial publicat de SNPAP Târgu Ocna."],
    ["2022-ist-027", "istorie", "concert-european", "Ordonați cronologic evenimentele: A. Negocierile de la Livadia, în Crimeea, între România și Rusia; B. Napoleon al III-lea amenință cu ruperea relațiilor cu Poarta; C. Bateriile de artilerie de la Calafat au bombardat Vidinul; D. Tratatul de la San Stefano.", ["BACD", "ABCD", "BCAD", "CDBA"], 0, S.hi2, "Răspuns conform baremului oficial publicat de SNPAP Târgu Ocna."],
    ["2022-ist-028", "istorie", "diplomatie-conflict", "Ordonați cronologic evenimentele: A. Ștefan cel Mare este nevoit să accepte plata tributului, în schimbul autonomiei; B. Sinan Pașa trece Dunărea cu o armată de circa 100 000 de oameni; C. Iancu de Hunedoara cucerește Niș și Sofia; D. Lupta de la Rovine.", ["DCAB", "DACB", "BCDA", "CADB"], 0, S.hi2, "Răspuns conform baremului oficial publicat de SNPAP Târgu Ocna."],
    ["2022-ist-029", "istorie", "romania-postbelica", "Ordonați cronologic evenimentele: A. Începe invazia germană în Uniunea Sovietică; B. Este semnat Dictatul de la Viena; C. Armata Roșie ocupă Bucureștiul; D. Regele Mihai I ordonă arestarea lui Mihai Antonescu.", ["BCDA", "CADB", "BADC", "ACDB"], 2, S.hi2, "Răspuns conform baremului oficial publicat de SNPAP Târgu Ocna."],
    ["2022-ist-030", "istorie", "diplomatie-conflict", "Ordonați cronologic evenimentele: A. Mircea cel Bătrân încorporează Dobrogea la Țara Românească; B. Sigismund de Luxemburg organizează Cruciada de la Nicopole; C. Mihai Viteazul obține victoria de la Giurgiu împotriva otomanilor; D. Proiectul lui Gabriel Bethlen de unire a Transilvaniei, Moldovei și Țării Românești într-un regat de confesiune protestantă.", ["ABCD", "BCAD", "BACD", "CABD"], 0, S.hi3, "Răspuns conform baremului oficial publicat de SNPAP Târgu Ocna."],
  ]);
})();
